modLoader="javafml"
loaderVersion="[35,)"
license="DBAD v1.1"

[[mods]]
modId="alchemist"
version="1.0"
displayName="Alchemist's Combatives"
credits="Gamedesign consultant and forever friend Cardigan."
authors="Lucie"
description="Alchemist's Combatives brings mixtures that can be put on weapons to give an advantage to fighting vile creatures."
