modLoader="javafml"
loaderVersion="[35,)"
license="DBAD v1.1"

[[mods]]
modId="alchemist"
version="2.0"
displayName="Alchemist's Combat 2"
credits="Gamedesign consultant and forever friend Cardigan."
authors="Lucie"
description="Alchemist's Combat 2 makes it possible to put potions on weaponry."
