modLoader="javafml"
loaderVersion="[35,)"
license="DBAD v1.1"

[[mods]]
modId="alchemist"
version="1.0"
displayName="Alchemist's Combat"
credits="Gamedesign consultant and forever friend Cardigan."
authors="Lucie"
description="Alchemist's Combat brings potions in the form of mixtures that can be put on weapons and give an advantage while fighting vile creatures."
