modLoader="javafml"
loaderVersion="[35,)"
license="DBAD v1.1"
logoFile="logo.png"
credits="Thank you: Ramona, Cardigan, Akitori, Muffinbarde"
authors="Lucie"

[[mods]]
modId="alchemist"
version="1.16.4-2.1.1"
displayName="Alchemist's Combat"
description="Alchemist's Combat makes it possible to put potions on weaponry."
